# KMS-SFDC Vector Database Configuration

# Salesforce Configuration
salesforce:
  # These should be set via environment variables for security
  username: ${SALESFORCE_USERNAME}
  password: ${SALESFORCE_PASSWORD}  
  security_token: ${SALESFORCE_SECURITY_TOKEN}
  login_url: ${SALESFORCE_LOGIN_URL}
  client_id: ${SALESFORCE_CLIENT_ID}
  client_secret: ${SALESFORCE_CLIENT_SECRET}
  api_version: "58.0"
  
  # Data extraction settings
  query_batch_size: 2000
  max_records: null  # null for no limit
  date_range_years: 2  # Extract 2 years of data

# Vector Database Configuration - Optimized for 2.5M+ cases
vectordb:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"  # Lightweight and reliable model
  embedding_dimension: 384  # all-MiniLM-L6-v2 dimension
  
  # Production-scale FAISS configuration
  faiss_index_type: "IndexIVFPQ"  # Inverted File + Product Quantization for large scale
  
  # Index parameters for 2.5M+ vectors
  nlist: 4096  # Number of clusters (sqrt of dataset size)
  m: 64        # Number of subquantizers (384 / 6 = 64 for optimal division)
  nbits: 8     # Bits per subquantizer
  
  # Processing batches optimized for GPU acceleration
  embedding_batch_size: 500     # Larger batches for GPU efficiency
  indexing_batch_size: 5000     # Larger batches for FAISS indexing
  search_batch_size: 1000       # Search batch size
  
  # Memory management
  use_gpu: true                # Use MPS (Metal Performance Shaders) on Mac
  memory_mapping: true         # Use memory mapping for large indexes
  precompute_table: true       # Precompute tables for faster search
  
  # Storage paths for production scale
  index_path: "data/faiss_index.bin"
  metadata_path: "data/case_metadata.json"
  temp_index_path: "data/temp_index.bin"      # For incremental updates
  backup_index_path: "data/backup_index.bin" # For rollback
  
  # Incremental update settings
  daily_update_batch_size: 10000    # Process daily updates in batches
  incremental_merge_threshold: 100000  # Rebuild after 100k incremental updates
  
  # Performance optimization
  search_nprobe: 128               # Search in 128 clusters (balance speed/accuracy)
  parallel_threads: 8              # Parallel processing threads
  chunk_size_mb: 1024             # Process data in 1GB chunks
  
# Text Processing
text_processing:
  min_text_length: 10
  max_text_length: 10000
  fields_to_vectorize:
    - "Case_Number"
    - "Subject_Description"
    - "Description_Description"
    - "Issue_Plain_Text"
    - "Cause_Plain_Text"
    - "Resolution_Plain_Text"
    - "Status_Text"
    - "TextBody"
    - "Description_Summary"
    - "Comment_Body_Text"
  
  preprocessing:
    remove_html: true
    remove_urls: true
    remove_emails: true
    lowercase: true
    remove_extra_whitespace: true

# Search Configuration
search:
  default_top_k: 10
  similarity_threshold: 0.4
  max_results: 50

# API Configuration
api:
  host: "0.0.0.0"
  port: 8008
  title: "KMS SFDC Vector Search API"
  version: "1.0.0"

# Logging
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  
# Monitoring
monitoring:
  enable_metrics: true
  metrics_port: 9090